# Generated by Django 4.0.4 on 2022-06-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_user_taskcategory_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='taskcategory',
            old_name='user',
            new_name='user_id',
        ),
    ]
