# Generated by Django 4.0.4 on 2022-06-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_task_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='taskcategory',
            old_name='user_id',
            new_name='user',
        ),
    ]
